/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int validCharNoEscape = 4;
  /** RegularExpression Id. */
  int validChar = 5;
  /** RegularExpression Id. */
  int escapeBody = 6;
  /** RegularExpression Id. */
  int hexChar = 7;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int BOOL = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int TYPE = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int PROC = 20;
  /** RegularExpression Id. */
  int CALL = 21;
  /** RegularExpression Id. */
  int WITH = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int DELETE = 24;
  /** RegularExpression Id. */
  int STRUCT = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int THEN = 28;
  /** RegularExpression Id. */
  int ELSE = 29;
  /** RegularExpression Id. */
  int SWITCH = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int DEFAULTT = 32;
  /** RegularExpression Id. */
  int NULL = 33;
  /** RegularExpression Id. */
  int READ = 34;
  /** RegularExpression Id. */
  int WRITE = 35;
  /** RegularExpression Id. */
  int PLUS = 36;
  /** RegularExpression Id. */
  int MINUS = 37;
  /** RegularExpression Id. */
  int MUL = 38;
  /** RegularExpression Id. */
  int DIV = 39;
  /** RegularExpression Id. */
  int MOD = 40;
  /** RegularExpression Id. */
  int EQEQ = 41;
  /** RegularExpression Id. */
  int NEQ = 42;
  /** RegularExpression Id. */
  int LESS = 43;
  /** RegularExpression Id. */
  int GREAT = 44;
  /** RegularExpression Id. */
  int LESSEQ = 45;
  /** RegularExpression Id. */
  int GREATEQ = 46;
  /** RegularExpression Id. */
  int OR = 47;
  /** RegularExpression Id. */
  int AND = 48;
  /** RegularExpression Id. */
  int OPEN_PAREN = 49;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 50;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 51;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 52;
  /** RegularExpression Id. */
  int OPEN_BRACE = 53;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 54;
  /** RegularExpression Id. */
  int NOT = 55;
  /** RegularExpression Id. */
  int COMMA = 56;
  /** RegularExpression Id. */
  int SEMICOLON = 57;
  /** RegularExpression Id. */
  int DOT = 58;
  /** RegularExpression Id. */
  int COLON = 59;
  /** RegularExpression Id. */
  int AMPERSAND = 60;
  /** RegularExpression Id. */
  int EQUAL = 61;
  /** RegularExpression Id. */
  int UNDERSCORE = 62;
  /** RegularExpression Id. */
  int ARROW = 63;
  /** RegularExpression Id. */
  int identificador = 64;
  /** RegularExpression Id. */
  int intNumber = 65;
  /** RegularExpression Id. */
  int realNumber = 66;
  /** RegularExpression Id. */
  int realPart = 67;
  /** RegularExpression Id. */
  int exponentialPart = 68;
  /** RegularExpression Id. */
  int stringLiteral = 69;
  /** RegularExpression Id. */
  int charLiteral = 70;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<validCharNoEscape>",
    "<validChar>",
    "<escapeBody>",
    "<hexChar>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<TRUE>",
    "<FALSE>",
    "<INT>",
    "<BOOL>",
    "<CHAR>",
    "<STRING>",
    "<DOUBLE>",
    "<TYPE>",
    "<VAR>",
    "<WHILE>",
    "<PROC>",
    "<CALL>",
    "<WITH>",
    "<NEW>",
    "<DELETE>",
    "<STRUCT>",
    "<DO>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<SWITCH>",
    "<CASE>",
    "<DEFAULTT>",
    "<NULL>",
    "<READ>",
    "<WRITE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"!\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\":\"",
    "\"&\"",
    "\"=\"",
    "\"_\"",
    "\"->\"",
    "<identificador>",
    "<intNumber>",
    "<realNumber>",
    "<realPart>",
    "<exponentialPart>",
    "<stringLiteral>",
    "<charLiteral>",
  };

}
