/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int validCharNoEscape = 4;
  /** RegularExpression Id. */
  int validChar = 5;
  /** RegularExpression Id. */
  int escapeBody = 6;
  /** RegularExpression Id. */
  int hexChar = 7;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int BOOL = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int TYPE = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int PROC = 20;
  /** RegularExpression Id. */
  int CALL = 21;
  /** RegularExpression Id. */
  int WITH = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int DELETE = 24;
  /** RegularExpression Id. */
  int identificador = 25;
  /** RegularExpression Id. */
  int numeroEntero = 26;
  /** RegularExpression Id. */
  int realNumber = 27;
  /** RegularExpression Id. */
  int realPart = 28;
  /** RegularExpression Id. */
  int exponentialPart = 29;
  /** RegularExpression Id. */
  int stringLiteral = 30;
  /** RegularExpression Id. */
  int charLiteral = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<validCharNoEscape>",
    "<validChar>",
    "<escapeBody>",
    "<hexChar>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<TRUE>",
    "<FALSE>",
    "<INT>",
    "<BOOL>",
    "<CHAR>",
    "<STRING>",
    "<DOUBLE>",
    "<TYPE>",
    "<VAR>",
    "<WHILE>",
    "<PROC>",
    "<CALL>",
    "<WITH>",
    "<NEW>",
    "<DELETE>",
    "<identificador>",
    "<numeroEntero>",
    "<realNumber>",
    "<realPart>",
    "<exponentialPart>",
    "<stringLiteral>",
    "<charLiteral>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"*\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"&&\"",
  };

}
