/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int TYPE = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int PROC = 13;
  /** RegularExpression Id. */
  int CALL = 14;
  /** RegularExpression Id. */
  int WITH = 15;
  /** RegularExpression Id. */
  int NEW = 16;
  /** RegularExpression Id. */
  int DELETE = 17;
  /** RegularExpression Id. */
  int identificador = 18;
  /** RegularExpression Id. */
  int numeroEntero = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<token of kind 4>",
    "<token of kind 5>",
    "<TRUE>",
    "<FALSE>",
    "<INT>",
    "<BOOL>",
    "<TYPE>",
    "<VAR>",
    "<WHILE>",
    "<PROC>",
    "<CALL>",
    "<WITH>",
    "<NEW>",
    "<DELETE>",
    "<identificador>",
    "<numeroEntero>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"*\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"&&\"",
  };

}
